### PR TITLE
fix: escape special chars when rendering Wasm module

### LINKED ISSUE #975: Special character in import/export name of Wasm module causes error
```wat
;; newline.wasm
(module (func (export "\n") (import "\n" "\n")))
```

When importing this module, the generated code contains invalid syntax.

```shellsession
$ echo 'import "./newline.wasm"' | deno run -
error: The module's source code could not be parsed: Expected ',', got 'string literal ( };, " };)' at …/newline.wasm:5:1

  " };
  ~~~~
$ deno --version
deno 2.1.0+0b8df9f (canary, release, aarch64-apple-darwin)
v8 13.0.245.12-rusty
typescript 5.6.2
```

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno_core/issues/975

### CODE REVIEW

File: core/modules/map.rs [hunk 1]
```diff
@@ -2067,16 +2074,19 @@ fn render_js_wasm_module(specifier: &str, wasm_deps: WasmDeps) -> String {
...
         ));
       } else {
         src.push(format!(
-          "export const {} = modInstance.exports.{};",
-          export_desc.name, export_desc.name
+          "const export{} = modInstance.exports[\"{}\"];\nexport {{ export{} as \"{}\" }};",
+          idx,
+          export_desc.name.escape_default(),
+          idx,
+          export_desc.name.escape_default()
```
Comment (dsherret) [inline core/modules/map.rs:2089]: Escape it once?

Comment (dsherret) [reply core/modules/map.rs:2089]: You can use positional arguments to only specify this once.

**Review by dsherret — APPROVED** [review]
LGTM, with one comment.
